name: CI/CD Workflow

on:
  push:
    branches:
      - main # Déclenche l'action sur les pushes vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Clonage du dépôt

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run tests
        run: |
          python -m unittest discover -s tests  # Exécute les tests
